apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  Labels:
    type: node-app
spec:
  template:
    metadata:
      name: my-first-pod
      Labels:
        type: node-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
  replica: 1
  selectore:
    matchLabels:
      type: node-app