apiVersion: v1
kind: Services
metadata:
  name: nginx-service
  Labels:
    type: node-app
spec:
  type: node-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32000
      protocol: TCP
  selectore: 
    type: node-app